# Thought Process
-> 5 genres are there with 1000 articles in total (taken for sample) </br>
-> bandit chooses 1 article </br>
-> reward is based on the genre of article chosen, whether it matches with the users </br>
-> if match, give points, if not match, can put 0 or negative </br>

In [85]:
import numpy as np
import pandas as pd

In [86]:
GENRES = [i for i in range(5)]

In [87]:
NUM_ARTICLES = 1000
article = [np.random.choice(GENRES) for _ in range(NUM_ARTICLES)]
article = pd.DataFrame(article, columns=["genre"])
article.to_csv("article.csv", index=False)

In [88]:
article

genre
0        3
1        0
2        0
3        3
4        3
..     ...
995      0
996      1
997      1
998      3
999      2

[1000 rows x 1 columns]

In [89]:
user_choices = article.genre
reward_correct = 2
reward_incorrect = -1

In [90]:
class MaB():
    def __init__(self, n_arms, eps = 0.8):
        self.n_arms = n_arms
        self.rewards = np.zeros(n_arms)
        self.counts = np.zeros(n_arms)
        self.eps = eps

    def select(self):
        if np.random.rand() < self.eps:
            return np.random.randint(self.n_arms)
        else:
            return np.argmax(self.rewards / (self.counts + 1))
        
    def update(self, arm, reward):
        self.counts[arm] += 1
        self.rewards[arm] += reward
        self.eps *= 0.99

    def output(self):
        arm = self.select()
        return arm
    
    def print_rewards(self):
        return self.rewards

    def print_counts(self):
        return self.counts

In [91]:
n_arms = 5
mab = MaB(n_arms)

for i in range(1000):
    out = mab.output()
    print(mab.rewards)
    print(mab.counts)
    if (out == user_choices[i]):
        reward = reward_correct
    else:
        reward = reward_incorrect
    mab.update(out, reward)
    print(out)
    

[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]
0
[-1.  0.  0.  0.  0.]
[1. 0. 0. 0. 0.]
1
[-1. -1.  0.  0.  0.]
[1. 1. 0. 0. 0.]
4
[-1. -1.  0.  0. -1.]
[1. 1. 0. 0. 1.]
3
[-1. -1.  0.  2. -1.]
[1. 1. 0. 1. 1.]
3
[-1. -1.  0.  4. -1.]
[1. 1. 0. 2. 1.]
0
[ 1. -1.  0.  4. -1.]
[2. 1. 0. 2. 1.]
0
[ 0. -1.  0.  4. -1.]
[3. 1. 0. 2. 1.]
1
[ 0. -2.  0.  4. -1.]
[3. 2. 0. 2. 1.]
2
[ 0. -2.  2.  4. -1.]
[3. 2. 1. 2. 1.]
4
[ 0. -2.  2.  4. -2.]
[3. 2. 1. 2. 2.]
3
[ 0. -2.  2.  3. -2.]
[3. 2. 1. 3. 2.]
4
[ 0. -2.  2.  3. -3.]
[3. 2. 1. 3. 3.]
2
[ 0. -2.  1.  3. -3.]
[3. 2. 2. 3. 3.]
3
[ 0. -2.  1.  2. -3.]
[3. 2. 2. 4. 3.]
2
[ 0. -2.  0.  2. -3.]
[3. 2. 3. 4. 3.]
3
[ 0. -2.  0.  1. -3.]
[3. 2. 3. 5. 3.]
1
[ 0.  0.  0.  1. -3.]
[3. 3. 3. 5. 3.]
3
[ 0.  0.  0.  0. -3.]
[3. 3. 3. 6. 3.]
2
[ 0.  0. -1.  0. -3.]
[3. 3. 4. 6. 3.]
0
[-1.  0. -1.  0. -3.]
[4. 3. 4. 6. 3.]
2
[-1.  0.  1.  0. -3.]
[4. 3. 5. 6. 3.]
2
[-1.  0.  0.  0. -3.]
[4. 3. 6. 6. 3.]
2
[-1.  0. -1.  0. -3.]
[4. 3. 7. 6. 3.]
0
[-2.  0. -1.  0. -3.]